### ISSUE TITLE
adding caption

### ISSUE THREAD

**Issue by beckybeq** [jedrzejchalubek/Glide.js#90]
Can I put some caption inside image slider?
--- 
I can put some caption but when image I swipe to next other images the caption disappear.
Here it is my code:
```html
<div class="slider">
			<ul class="slider__wrapper">
				<li class="slider__item">
					<img src="http://dummyimage.com/384x230/eaeaea/8083ad.gif">
					<div class="slider__info">
						<h3>Lorem ipsum dolor sit amet, consectetur adipisicing AAA.</h3>
					</div>
				</li>
				<li class="slider__item">
					<img src="http://dummyimage.com/384x230/fafafa/8083ad.gif">
					<div class="slider__info">
						<h3>Lorem ipsum dolor sit amet, consectetur adipisicing BBB.</h3>
					</div>
				</li>
				<li class="slider__item">
					<img src="http://dummyimage.com/384x230/b3b3b3/8083ad.gif">
					<div class="slider__info">
						<h3>Lorem ipsum dolor sit amet, consectetur adipisicing CCC.</h3>
					</div>
				</li>
			</ul>
		</div><!-- /slider -->
```
```css
.slider__item {
  height: 100%;
  float: left;
  clear: none;
}
.slider__item img {
  width: 100%;
}
.slider__info {
  background: rgba(0, 0, 0, 0.35);
  left: 0;
  bottom: 5px;
  position: absolute;
}
.slider__info h3 {
  font-size: 1.5em;
  color: #fff;
}
.slider__info p {
  font-size: 10px;
}
```

![head1](https://cloud.githubusercontent.com/assets/3049864/7135317/a8c334c6-e2cf-11e4-8717-66fa157eab80.png)

![head2](https://cloud.githubusercontent.com/assets/3049864/7135322/b0f53310-e2cf-11e4-83f8-3eb1ca78f7e1.png)
